# Generated by Django 6.0.5 on 2026-05-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='NYONDO General Hardware LTD', max_length=255)),
                ('business_phone', models.CharField(default='+256-XXX-XXX-XXXX', max_length=20)),
                ('business_email', models.EmailField(default='info@nyondohardware.com', max_length=254)),
                ('transport_rate_per_km', models.DecimalField(decimal_places=2, default=3000.0, max_digits=8, verbose_name='Transport Rate (UGX per km)')),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Free Delivery Threshold (UGX)')),
                ('default_low_stock_threshold', models.IntegerField(default=5, verbose_name='Default Low Stock Alert')),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('timezone', models.CharField(default='UTC+3', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
