# Generated by Django 6.0.5 on 2026-05-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Accounts / Admin'), ('SALES', 'Sales Attendant'), ('STOCK', 'Store Manager')], default='SALES', max_length=20),
        ),
    ]
